nuget-package:
  stage: package
  needs:
  - job: build-debug
    artifacts: false
  - job: build-release
    artifacts: false
  - job: test
    artifacts: false
  variables:
    GIT_DEPTH: 0
  script:
    - VERSION="$(./get_version_from_git.sh)${CI_COMMIT_BRANCH:+-${CI_COMMIT_BRANCH:0:63}}"
    - 'cd ${PACKAGE_NAME}'
    - 'dotnet pack -c Release -p:Version="${VERSION}"'
    - 'dotnet nuget add source "${CI_API_V4_URL}/projects/${PACKAGE_REPO_PROJECT_ID}/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text'
    - 'dotnet nuget push "bin/Release/${PACKAGE_NAME}.${VERSION}.nupkg" --source gitlab --symbol-source gitlab'
  parallel:
    matrix:
    - PACKAGE_NAME: "SGL.Utilities"
    - PACKAGE_NAME: "SGL.Utilities.Backend"
    - PACKAGE_NAME: "SGL.Utilities.Backend.AspNetCore"
    - PACKAGE_NAME: "SGL.Utilities.Backend.BlobStore"
    - PACKAGE_NAME: "SGL.Utilities.Backend.Security"
    - PACKAGE_NAME: "SGL.Utilities.Backend.TestUtilities"
    - PACKAGE_NAME: "SGL.Utilities.Crypto"
    - PACKAGE_NAME: "SGL.Utilities.Crypto.EntityFrameworkCore"
    - PACKAGE_NAME: "SGL.Utilities.Crypto.AspNetCore"
    - PACKAGE_NAME: "SGL.Utilities.Logging"
    - PACKAGE_NAME: "SGL.Utilities.PrometheusNet"
    - PACKAGE_NAME: "SGL.Utilities.TestUtilities.XUnit"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_TAG =~ /^\d+(\.\d+)*$/'
